---
title: "P8105_hw6_ym2715"
author: "Yizhi Ma"
date: "11/26/2018"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(modelr)
```

## Problem 1

```{r data loading and wrangling, message=FALSE, warning=FALSE}
homi_raw = read_csv("https://raw.githubusercontent.com/washingtonpost/data-homicides/master/homicide-data.csv")

homi = homi_raw 
homi$city_state = paste(homi$city, homi$state, sep = ", ")
homi = homi %>% 
  select(-city, -state) %>% 
  filter(city_state != "Dallas, TX",
         city_state != "Phoenix, AZ",
         city_state != "Kansas City, MO",
         city_state != "Tulsa, AL") %>% 
  mutate(victim_race = case_when(victim_race == "White" ~ "white",
                                 TRUE ~ "non-white"),
         victim_race = fct_relevel(victim_race, ref = "white"),
         victim_age = as.numeric(victim_age))
```

```{r logistic regression in Balto}
balto_glm = homi %>% 
  filter(city_state == "Baltimore, MD") %>% 
  mutate(disposition = case_when(disposition == "Closed by arrest" ~ 1,
                                 TRUE ~ 0))%>% 
  glm(disposition ~ victim_age + victim_sex + victim_race, data = ., family = binomial())

balto_glm %>% broom::tidy(conf.int = TRUE)

balto_or_ci = balto_glm %>% 
  broom::tidy(conf.int = TRUE) %>% 
  mutate(odds_ratio = exp(estimate),
         conf_lower = exp(conf.low),
         conf_upper = exp(conf.high)) %>% 
  select(term, odds_ratio, conf_lower, conf_upper) %>% 
  filter(term == "victim_racenon-white")

```

```{r regression for each city, warning=FALSE}
each_city_glm = homi %>% 
  mutate(disposition = case_when(disposition == "Closed by arrest" ~ 1,
                                 TRUE ~ 0))%>% 
  group_by(city_state) %>% 
  nest() %>% 
  mutate(model = map(data, ~glm(disposition ~ victim_age + victim_race + victim_sex, 
                                    data = ., family = binomial())),
         model_ci = map(model, broom::confint_tidy),
         model_tidy = map(model, broom::tidy)) %>% 
  select(-data, -model) %>% 
  unnest() %>% 
  filter(term == "victim_racenon-white") %>% 
  mutate(odds_ratio = exp(estimate), conf.low = exp(conf.low), conf.high = exp(conf.high)) %>% 
  select(city_state, odds_ratio, conf.low, conf.high)
```

```{r plot for each city}
each_city_glm %>% 
  arrange(odds_ratio) %>% 
  mutate(city_state = factor(city_state, unique(city_state))) %>% 
  ggplot(aes(x = city_state, y = odds_ratio)) +
  geom_point(alpha = 0.8) +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high), alpha = 0.4) +
  coord_flip() +
  labs(
    title = "Odds ratio and CIs for solved homicide cases in each city",
    x = "City, State",
    y = "Odds ratio (non-white vs white) and Confidence interval",
    caption = "data from The Washington Post "
  ) +
  theme_bw()+
  theme(axis.text.y = element_text(size = 6, hjust = 1)) 
```

## Problem 2

```{r data load and wrangling, message=FALSE}
birthweight_raw = read_csv("http://p8105.com/data/birthweight.csv")

birthweight_tidy = 
  birthweight_raw %>% 
  select(bwt, everything()) %>% 
  mutate(babysex = as.factor(case_when(babysex == 1 ~ "male",
                                       babysex == 2 ~ "female")),
         frace = as.factor(frace),
         mrace = as.factor(mrace),
         frace = recode(frace,
                        "1" = "White", "2" = "Black", "3" = "Asian", "4" = "Puerto Rican", "8" = "Other", "9" = "Unknown"),
         mrace = recode(mrace,
                        "1" = "White", "2" = "Black", "3" = "Asian", "4" = "Puerto Rican", "8" = "Other"))


```

```{r fit my model}
myfit = lm(bwt ~ ., data = birthweight_tidy)
step(myfit, direction = 'backward')
model_exp = lm(bwt ~ babysex + bhead + blength + delwt + 
             fincome + gaweeks + mheight + mrace + parity + ppwt + smoken, 
             data = birthweight_tidy)
summary(model_exp)
```

```{r plot my model}
birthweight_tidy %>% 
  add_predictions(model_exp) %>% 
  add_residuals(model_exp) %>% 
  ggplot(aes(x = pred, y = resid)) +
  geom_point(alpha = 0.3) +
  labs(
        title = "Residuals VS Fitted Values",
        x = "Fitted Values",
        y = "Residuals"
      ) 
```


```{r comparision model 1}
model_c1 = lm(bwt ~ blength + gaweeks, 
              data = birthweight_tidy)
summary(model_c1)
```


```{r comparision model 2}
model_c2 = lm(bwt ~ bhead + blength + babysex + bhead*blength + blength*babysex +  bhead*babysex + bhead*blength*babysex, 
              data = birthweight_tidy)
summary(model_c2)
```

```{r compare}
cv_df =
  crossv_mc(birthweight_tidy, 100) %>% 
  mutate(train = map(train, as_tibble),
         test = map(test, as_tibble)) %>% 
  mutate(model_exp = map(train, ~lm(bwt ~ babysex + bhead + blength + delwt + fincome + gaweeks 
                                    + mheight + mrace + parity + ppwt + smoken, 
                                    data = birthweight_tidy)),
         model_c1  = map(train, ~lm(bwt ~ blength + gaweeks, 
                                    data = birthweight_tidy)),
         model_c2  = map(train, ~lm(bwt ~ bhead + blength + babysex + bhead*blength 
                                    + blength*babysex + bhead*babysex + bhead*blength*babysex, 
                                    data = birthweight_tidy))) %>% 
  mutate(rmse_exp= map2_dbl(model_exp,test, ~rmse(model = .x, data = .y)),
         rmse_c1 = map2_dbl(model_c1, test, ~rmse(model = .x, data = .y)),
         rmse_c2 = map2_dbl(model_c2, test, ~rmse(model = .x, data = .y)))

cv_df %>% 
  select(starts_with("rmse")) %>% 
  gather(key = model, value = rmse) %>% 
  mutate(model = str_replace(model, "rmse_", ""),
         model = fct_inorder(model)) %>% 
  ggplot(aes(x = model, y = rmse)) + 
  geom_violin(fill = "slategray1")
```


